apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: default
spec:
  project: frontend
  source:
    repoURL: https://github.com/realexcel2021/finops-kubernetes-cluster.git
    targetRevision: HEAD
    path: nginx-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default