
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prestashop-app
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prestashop
    server: https://kubernetes.default.svc 
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: prestashop
    targetRevision: 20.2.3
    helm:
      values: |
        replicaCount: 1
        prestashopUsername: admin
        prestashopPassword: "12345678HJ"
        persistence:
          enabled: false
        mariadb:
          enabled: true
          auth:
            rootPassword: "12345678HJ"
            password: "12345678HJ"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true