
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-app
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc 
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 19.2.3
    helm:
      values: |
        replicaCount: 1
        wordpressUsername: ""
        wordpressPassword: ""
        persistence:
          enabled: false
        mariadb:
          enabled: true
          auth:
            rootPassword: ""
            database: ""

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true